name       : networkmanager-l2tp
version    : 1.8.6
release    : 6
source     :
    - https://github.com/nm-l2tp/NetworkManager-l2tp/releases/download/1.8.6/NetworkManager-l2tp-1.8.6.tar.xz : e345263c440ef8f48bcd95661d7772ffdbdd65e37d0a3eca813a542a3357ac23
license    : GPL-2.0-or-later
component  : network.base
summary    : L2TP and L2TP/IPsec support for NetworkManager
description: |
    NetworkManager-l2tp is a VPN plugin for NetworkManager which provides support for L2TP and L2TP/IPsec (i.e. L2TP over IPsec) connections.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-1)
    - pkgconfig(nss)
    - ppp-devel
rundeps    :
    - libreswan
    - xl2tpd
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
