name       : networkmanager-l2tp
version    : 1.2.12
release    : 1
source     :
    - https://github.com/nm-l2tp/NetworkManager-l2tp/archive/1.2.12.tar.gz : 470739336e5075d94b05ac75edb00a8249a9cd194f026dc4cbe96155be5b05a6
license    : GPL-2.0-or-later
component  : network.base
summary    : L2TP and L2TP/IPsec support for NetworkManager
description: |
    NetworkManager-l2tp is a VPN plugin for NetworkManager which provides support for L2TP and L2TP/IPsec (i.e. L2TP over IPsec) connections.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-1)
    - ppp-devel
rundeps    :
    - libreswan
    - xl2tpd
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
