name       : networkmanager-l2tp
version    : 1.2.16
release    : 3
source     :
    - https://github.com/nm-l2tp/NetworkManager-l2tp/releases/download/1.2.16/NetworkManager-l2tp-1.2.16.tar.xz : af32f48a6e2a65c7ea44a9749cc48ce5222df70971dd826582a238696ce58c33
license    : GPL-2.0-or-later
component  : network.base
summary    : L2TP and L2TP/IPsec support for NetworkManager
description: |
    NetworkManager-l2tp is a VPN plugin for NetworkManager which provides support for L2TP and L2TP/IPsec (i.e. L2TP over IPsec) connections.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-1)
    - ppp-devel
rundeps    :
    - libreswan
    - xl2tpd
setup      : |
    %configure --disable-static --with-pppd-plugin-dir=%libdir%/pppd/2.4.8/
build      : |
    %make
install    : |
    %make_install
